### ISSUE TITLE
[GUIDE] Play in realtime

### ISSUE THREAD

**Issue by lars18th** [piratfm/eti-tools#14]
Hi,

I share this here only as a reference:

- If you like to play in realtime from the satellite, then you can now do it!
- First read the "brute-force-workaround" decribed in: http://github.com/AlbrechtL/welle.io/issues/217
- Then replace the command described in the README:
-- `socat UDP4-RECV:1234,bind=239.1.1.1,ip-add-membership=239.1.1.1:eth0,reuseaddr - | ts2na -p 1061 -s 12 | na2ni -o bbc.eti-ni`.
-- with this one...
-- `socat UDP4-RECV:1234,bind=239.1.1.1,ip-add-membership=239.1.1.1:eth0,reuseaddr - | ts2na -p 1061 -s 12 | na2ni | ./odr-dabmod-next -f ./raw-fifo -F u8`.
-- Hint: The "odr-dabmod-next" is the ODR-DabMod tool from the 'next' branch.
- Then run the modded `rtl_mus.py` tool, and open your preferable DAB Player with RTL_TCP input support.

That's all! :smile:

**Comment by lars18th** [comment]
Hi,

A simplification without using the `rtl_mus.py` tool:

- `socat UDP4-RECV:5018,bind=239.1.1.10,ip-add-membership=239.1.1.10:eth0,reuseaddr - | ./ts2na -p 1061 -s 12 | ./na2ni | ./odr-dabmod-next -f /dev/stdout -F u8 | nc -l -k -q -1 0.0.0.0 1234`

Enjoy yourselves!

**Comment by andimik** [comment]
@lars18th 
I don't understand your guide (like some other freaks from Germany who asked me for help after reading that) at all, BTW ... Your guide does not contain how to tune to the frequency.

Today I tried hours to do this in real-time, no chance. 

`dvbstream -f 12645000 -s 1490 -o 8192 -p V -D 1 > /dev/stdout | sleep 5 && ts2na  -s -3 | na2ni | ni2http --list`
or
`dvbstream -f 12641000 -s 1340 8192 -p V -D 1 -o | ts2na -s -3 | na2ni | dablin_gtk`

does not work for WDR (dish is on 23.5 East, 1 LNB). 


> Bit error rate: 0
> Signal strength: 41984
> SNR: 65535
> UNC: 0
> FE_STATUS: FE_HAS_SIGNAL FE_HAS_LOCK FE_HAS_CARRIER FE_HAS_VITERBI FE_HAS_SYNC
> dvbstream will stop after -1 seconds (71582788 minutes)
> Output to stdout
> Streaming 1 stream
> **ERROR: Can't find sync**



It locks, but the content seems not to be what ts2na expects ...

When I record the TS in Windows and change to Linux and do then ts2na and na2ni then it works ... (This workaround with file recording in Windows and processing it in Linux I'm doing for around 2 years.)

But these transponders (in DVB-S) work: 

`dvbstream -f 11683000 -s 2734 8192 -p V -D 1 -o > /tmp/kitchen.ts`
or
`dvbstream -f 12168000 -s 27500 8192 -p V -D 1 -o | vlc -` 

Can you tell me what I'm doing wrong?

**Comment by andimik** [comment]
The readme has some examples. So let's close this.
