### ISSUE TITLE
Idea: ni2eti_tcp server tool

### ISSUE THREAD

**Issue by lars18th** [piratfm/eti-tools#15]
Hi,

I like to know your opinion about the idea to incorporate a new tool to the "eti-tools" package:

- The name of the tool will be `ni2eti_tcp`.
- The source skeleton can be derived from the current `ni2http` code.
- This tool can input ETI-NI frames from one or more files, even from fifos.
- The output is a TCP listening socket with one ETI-NI bitstream.
- The TCP protocol is based on the RTL_TCP format.
- The command line will be `usage: ./ni2eti_tcp [-i <inputfile1>:freq1,<inputfile2>:freq2,<inputfile3>:freq3,...] [ip:port]`.

And regarding the TCP protocol, a brief description:

- It starts with 12 bytes with a format description: `ETI-NI\0\0\0\0\0\0` (in the future other formats can be supported) (any string starting with `RTL` will be forbidden).
- After initial 12 bytes the ETI-NI bitstream is sended byte-to-byte in chuncks of 6144 bytes.
- At any time, the server will accept commands in the form of the RTL_TCP protocol. See http://github.com/osmocom/rtl-sdr/blob/master/src/rtl_tcp.c#L306
- Only the command `0x01` (Set Frequency) is accepted, all others be discarded.
- The command "Set Frequency" will be used for charging the source (inputfile1, inputfile2, etc.).

And for the first iteration the support for charging the frequency and use multiple inputs isn't required.
How do you feel about this?

**Comment by piratfm** [comment]
And who's frequency it must change, since ni2http doesn't do any DAB/DVB front-end handling at all?

**Comment by piratfm** [comment]
Anyway, are You sure that such or similar tool doesn't exists yet?
Maybe You will be happy with 
https://githb.com/JvanKatwijk/dab-cmdline 
https://github.com/linuxstb/dabtools
or even
https://github.com/AlbrechtL/RTKDAB_Interface (for win32)

**Comment by lars18th** [comment]
Hi @piratfm ,

Perhaps I'm not explained very well!
I'll try to clariry some aspects:

- This tool `ni2eti_tcp` streams ETI-NI frames, not IQ samples (like RTL_TCP tools do), even if it uses _similar_ TCP transport protocol.
- This tool can read ETI-NI frames from other tools like `dab-cmdline` or `dab2eti` that demodulate RF DAB signals or IQ samples.
- This tool can read too ETI-NI frames from tools like `ts2na`+`na2ni` or `edi2eti` that gets the bitstream from network streams.

The objective is have a "simple" TCP server that can provide in realtime the ETI-NI bitstream and change the source (using the frequency). Then, any DAB player can incorporate this ETI_TCP input for receiving the ensamble.

I hope it's now more clear. :smile:

**Comment by lars18th** [comment]
(off topic)

@piratfm , you're the owner of this page: http://tipok.org.ua/node/46 ?

**Comment by piratfm** [comment]
Yes,
And I'm going to close thiss issue as won'tfix because You are describing what exactly ZeroMQ protocol do.

Becasue edi2eti and ni2http can be used to stream ETI over ZeroMQ protocol. Other features - are out-of-focus regarding to those tools.

**Comment by lars18th** [comment]
Hi @piratfm ,

> And I'm going to close thiss issue

OK. Perhaps this proposal isn't the best solution.

> Becasue edi2eti and ni2http and zmq-sub can be used to stream ETI over ZeroMQ protocol. Other features - are out-of-focus regarding to those tools.

Regarding the ZeroMQ protocol, the problem is that the protocol isn't transparent. A simple "socat" or "netcat" can't impersonate this protocol. This is the reason to make a proposal of some simple TCP transport protocol.

> TCP server with possibility to change frequency - is feature that needs to be implemented on receiver front-ends like dab-cmdline or dab2eti

Yes, this the other reason to propose this protocol. In any case, another "dirty" solution can be:

- Use one TCP port for one frequency, like `tcp://localhost:10001` for ETI-NI bitstream with the Freq.1, and "10002" for Freq.2, etc.
- Run one ETI souce for each Frequency, and use "socat" for convert from the STDOUT to the corresponding TCP listening socket.

However, the problem here is when you use RF tuners. In this case, when using the "dab-cmdline" or "dab2eti" tools you need to launch them on-demand.

What you think?
