### ISSUE TITLE
edi2eti: allow STDIN for input

### ISSUE THREAD

**Issue by basicmaster** [piratfm/eti-tools#33]
It would be great if `stdin` could be used as input, instead of an UDP stream....this would allow to use e.g. other sources or dumps.

**Comment by andimik** [comment]
@basicmaster 
Can we close this issue as `fedi2eti` does it already?

**Comment by basicmaster** [comment]
The original reason for this request was to somehow use (non-multicast) EDI streams with DABlin. As meanwhile DABlin has built-in EDI support, this request is outdated and can be closed.
