### ISSUE TITLE
Config file for ni2out

### ISSUE THREAD

**Issue by antonioag95** [piratfm/eti-tools#39]
As far as I can read, it seems that ni2http used the parameter "-c" in order to take a config file as input, I can't find the way to import a config file for ni2out. Any help?

**Comment by andimik** [comment]
Thanks for the hint, the Readme seems to be not up-to-date.

You could use an older fork, for example https://github.com/athoik/eti-tools

@athoik Dear Athanasios, 
Could you answer him? As far as I can remember it happened here: 

https://github.com/athoik/eti-tools/commit/e40d87f0b3fec7c0dfeb2ffdb0400a1b44ee7feb

https://github.com/athoik/eti-tools/compare/master...piratfm:master

**Comment by andimik** [comment]
Although I'm not a programmer, I found out that you have to edit the `Makefile` file, then it also works with the current version.

1. add this line
`CFLAGS+=-I. -Ilibshout-2.2.2/include`

2. and the line
`all: cleanapps ni2out ts2na na2ts na2ni edi2eti fedi2eti mpe2aac mpe2mpa mpe2ts dvb-ip-mpe2ts eti2zmq` 
just replace by
`all: cleanapps ni2out ts2na na2ts na2ni edi2eti fedi2eti mpe2aac mpe2mpa mpe2ts dvb-ip-mpe2ts eti2zmq ni2http`

**Comment by antonioag95** [comment]
Thank you! Now it compiles "ni2http" just fine!
