### ISSUE TITLE
dvb-ip-mpe2ts not installed

### ISSUE THREAD

**Issue by picatchoof** [piratfm/eti-tools#48]
Hello all
Please need your help
I tried to compile and install the Tools but the DVB-IP-MPE2TS did not show after the Installation is finished.
thanx a lot for your help

**Comment by andimik** [comment]
Strange, I can't confirm. Please note that this is case sensitive

```
dvb-ip-mpe2ts -h

Usage: dvb-ip-mpe2ts [OPTIONS]
----------------------------------------------
dvb-ip-mpe2ts v0.7a 22/11/2018

Extract ts-file:
-i,	DVB-IP-MPE TS input file ('-' for STDIN)
-o,	extracted TS output file ('-' for STDOUT)
-p,	pid to be processed
-a,	destination IP-address, e.g. 127.0.0.1
-n,	destination port, e.g. 3000

Scan file for pids, destination IP-addresses and port:
-s,	number of valid TS packets with pusi to be scanned in DVB-IP-MPE TS input file, e.g 100
-i,	DVB-IP-MPE TS input file ('-' for STDIN)

Help:
-h,	print this help
```

**Comment by picatchoof** [comment]
Hello all.
Sorry for that.
I did all as described in the readme file.

The error was from the G++ 
So I installed the build-essential and redo the make and make install and it goes well.

Best regards.
Appreciate your help.
